version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_campparty
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=campparty
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_ADDRESS=172.17.0.1
networks:
  default:
    external:
      name: wxcb0
